CI: Fix Rust triplet identification
On recent Rust or Cargo versions, they stopped being able to handle the
default host triplet in our x86_64 images:

    ERROR: Don't know how to translate x86_64-pc-linux-gnu for rustc

Specify the host triplet on the configure command line.

No change is needed for aarch64, so we need to split those jobs and not
use the YAML variables.