gerror: Root define_error_properties()
This function now requires a rooted object, since the
JS_DefinePropertyById() calls require one as well.

https://bugzilla.gnome.org/show_bug.cgi?id=776966