profiler: Use std::array instead of stack array
In newer Clang the stack allocation of the array produces the odd
-Walign-mismatch message:

error: passing 1-byte aligned argument to 8-byte aligned parameter
'this' of '' may result in an unaligned pointer access

Using std::array seems to solve the problem.

(cherry picked from commit b0ec751f5f0244e57c713f57132c06d6899d3387)