gerror: Split private struct into ErrorPrototype/ErrorInstance
This continues the ports of GObject introspection wrappers to the new
framework introduced in wrapperutils.h.

As part of being ported to the new code, GError objects now gain a
$gtype property, as all the rest of the GObject introspection wrappers
have. This property will always be equal to G_TYPE_ERROR.