build: Add requirement on sysprof 3.33.2
Profiling requires sysprof 3.33.2 because it uses a newer API recently
introduced in sysprof: `sysprof_capture_writer_set_flush_delay()`

The configure script does not check for the sysprof version and using an
older version of sysprof will cause a build failure later on:

```
gjs/profiler.cpp:445:5: error: ‘sysprof_capture_writer_set_flush_delay’
was not declared in this scope; did you mean ‘sysprof_capture_writer_set_counters’?
  445 |     sysprof_capture_writer_set_flush_delay(self->capture,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     sysprof_capture_writer_set_counters
  CC       libgjs-private/libgjs_la-gjs-gtk-util.lo
make[1]: *** [Makefile:2543: gjs/libgjs_la-profiler.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
```

Add an explicit dependency on sysprof 3.33.2 to avoid the build failure.

https://gitlab.gnome.org/GNOME/gjs/issues/258