gerror: Move to C++-style API
This allows cleaning up the public API in gerror.h a bit, adding missing
error checks in calling code, removing C API that only called C++ API,
and creating an ErrorInstance::object_for_c_ptr() method.

The idea is to gradually provide more typesafe, C++-style APIs for all
of the GI wrapper classes, and change calling code to use them rather
than the old C-style APIs.