CI: Handle precompiled headers in iwyu command line
I'm not sure if this has always been broken since we added precompiled
headers, or if it's been broken recently by an iwyu upgrade. But
apparently we need to add this extra argument, otherwise we get 'fatal
error: gjs_pch.hh file not found'.