gerror: Pass null JSPrincipals to saved frame API calls
The saved frame API now requires a pointer to JSPrincipals. According to
the SpiderMonkey developers, we can just pass null here and ignore it
unless we are using JS_SetSecurityCallbacks(), which we are not.