gi/boxed.cpp: fix `gcc-16` build
On upcoming `gcc-16` `gjs` fails the build as:

    ...-gcc-16.0.0.99999999/include/c++/16.0.0.99999999/bits/predefined_ops.h:105:47: error:
      cannot bind rvalue reference of type 'GI::OwnedInfo<GI::InfoTag::FIELD>&&' to lvalue of type 'GI::OwnedInfo<GI::InfoTag::FIELD>'
      105 |         operator()(_Tp&& __arg) { return !_M_f(__arg); }
          |                                           ~~~~^~~~~~~
    In file included from ../gi/arg.h:19,
                     from ../gi/boxed.cpp:39:
    ../gi/info.h:372:27: note: initializing argument 1 of 'GI::OwnedInfo<TAG>::OwnedInfo(GI::OwnedInfo<TAG>&&) [with GI::InfoTag TAG = GI::InfoTag::FIELD]'
      372 |     OwnedInfo(OwnedInfo&& other) : OwnedInfo(other.m_info) {
          |               ~~~~~~~~~~~~^~~~~
    ../gi/boxed.cpp:901:35: note: initializing argument 1 of 'struct_is_simple<GI::InfoTag::STRUCT>(const GI::UnownedInfo<GI::InfoTag::STRUCT>&)::<lambda(GI::AutoFieldInfo)>'
      901 |         iter.begin(), iter.end(), [](GI::AutoFieldInfo field_info) {
          |                                   ^

I think this happens because `GI::AutoFieldInfo` has no implicit
copying constructor. Let's use the reference instead.